import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from '../context/AuthContext';
import { CartProvider } from '../context/CartContext';
import { SessionProvider } from '../context/SessionContext';
import { NotificationProvider } from '../context/NotificationContext';
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_SITE_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NotificationProvider>
          <AuthProvider>
            <SessionProvider>
              <CartProvider>
                {children}
              </CartProvider>
            </SessionProvider>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
